# Generated by Django 4.2.5 on 2023-09-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('aqaid_f', models.IntegerField()),
                ('quran_t', models.IntegerField()),
                ('arabic1', models.IntegerField()),
                ('arabic2', models.IntegerField()),
                ('bangla', models.IntegerField()),
                ('english', models.IntegerField()),
                ('math', models.IntegerField()),
                ('gen_science', models.IntegerField()),
                ('b_world', models.IntegerField()),
                ('ict', models.IntegerField()),
                ('gpa', models.IntegerField()),
                ('gread', models.CharField(max_length=20)),
            ],
        ),
    ]
